increment-version:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: increment
            command: bash .circleci/bash-increment-version.bash
